version: '3.8'

services:
  receipt-processor:
    build: .
    image: receipt-processor-app
    container_name: receipt-processor
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis-server:6379
    networks:
      - receipt-processor-network

  redis:
    image: redis:latest
    container_name: redis-server
    environment:
      - REDIS_ADDR=redis-server:6379
    ports:
      - "6379:6379"
    networks:
      - receipt-processor-network

networks:
  receipt-processor-network:
    driver: bridge