version: '3.8'
services:
  receipt-processor:
    build: .
    image: receipt-processor-app
    container_name: receipt-processor
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SERVER_PORT=:8080
      - REDIS_ADDR=redis:6379

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"